import React from 'react';
import Head from "next/head";
import Link from 'next/link';

type LayoutProps = {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = (props: LayoutProps) => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header
        className="container flex flex-col items-start justify-center mx-auto w-11/12 xl:w-4/5 p-4 bg-slate-200"
      >

        {/* navi */}
        <nav className="flex flex-row items-center justify-start h-20 px-4 py-1 gap-8">
            <Link
              href="/"
            >
              <a className='hover:underline'>sleep</a>
            </Link>
            <Link
              href="/info"
            >
              <a className='hover:underline'>info</a>
            </Link>
        </nav>

        <section className='flex flex-row items-center justify-start p-4'>
          <h1 className="text-3xl md:text-[3rem] leading-normal font-extrabold text-gray-700">
              Sleep <span className="text-purple-300">Cycle</span> Calculator
          </h1>
        </section>

      </header>

      <main className="container flex flex-col items-start justify-center mx-auto w-11/12 xl:w-4/5 p-4 min-h-[40vh] bg-slate-300">
        {props.children}
      </main>
    </>
  )
}

export default Layout;